### ISSUE TITLE
Microsoft .NET Framework exception @ Creating nodes by tier (03)

### ISSUE THREAD

**Issue by LEEYOL** [mikeoverbay/TankExporter#122]
As seen in the title I am getting an error from .NET Frameworking after the program has started and it automatically loads the res.
I am using Win 11
Here is the error txt:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Tank_Exporter.frmMain.store_in_treeview(Int32 i, TreeView& tn)
   at Tank_Exporter.frmMain.load_tabs()
   at Tank_Exporter.frmMain.frmMain_Load(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by mikeoverbay** [comment]
Hi
This line
`System.NullReferenceException: Object reference not set to an instance of an object.
at Tank_Exporter.frmMain.store_in_treeview(Int32 i, TreeView& tn)`
is telling us that tn (tree node) does not contain a valid tree node.
Update the game if you have not. Its possible the data from the wot server isn't found in the game data.
If that doesn't work, or does... let me know, okay?

**Comment by LEEYOL** [comment]
Yes,
I didn't update WoT for a while.
Thanks, that resolved the issue.
