### ISSUE TITLE
Unable to load DLL 'TextureLoader.dll'

### ISSUE THREAD

**Issue by Windows200000** [mikeoverbay/TankExporter#130]
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.DllNotFoundException: Unable to load DLL 'TextureLoader.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Tank_Exporter.modGlobals.initGlew()
   at Tank_Exporter.frmMain.frmMain_Load(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
!_Tank Exporter
    Assembly Version: 1.0.0.165
    Win32 Version: 1.0.0.165
    CodeBase: file:///C:/Program%20Files%20(x86)/Coffee_/Tank%20Exporter/!_Tank%20Exporter.exe
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9206.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9200.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
SharpDX.Mathematics
    Assembly Version: 4.2.0.0
    Win32 Version: 4.2.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Coffee_/Tank%20Exporter/SharpDX.Mathematics.DLL
----------------------------------------
Ionic.Zip
    Assembly Version: 1.9.1.8
    Win32 Version: 1.9.1.8
    CodeBase: file:///C:/Program%20Files%20(x86)/Coffee_/Tank%20Exporter/Ionic.Zip.DLL
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9191.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
FbxSDK
    Assembly Version: 1.0.4593.24947
    Win32 Version: 
    CodeBase: file:///C:/Program%20Files%20(x86)/Coffee_/Tank%20Exporter/FbxSDK.DLL
----------------------------------------
cttools
    Assembly Version: 1.0.4723.22902
    Win32 Version: 
    CodeBase: file:///C:/Program%20Files%20(x86)/Coffee_/Tank%20Exporter/cttools.DLL
----------------------------------------
msvcm90
    Assembly Version: 9.0.30729.9635
    Win32 Version: 9.00.30729.9635
    CodeBase: file:///C:/Windows/WinSxS/x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9635_none_508ff82ebcbafee0/msvcm90.dll
----------------------------------------
Tao.DevIl
    Assembly Version: 1.6.8.3
    Win32 Version: 1.6.8.3
    CodeBase: file:///C:/Program%20Files%20(x86)/Coffee_/Tank%20Exporter/Tao.DevIl.DLL
----------------------------------------
Tao.OpenGl
    Assembly Version: 2.1.0.12
    Win32 Version: 2.1.0.12
    CodeBase: file:///C:/Program%20Files%20(x86)/Coffee_/Tank%20Exporter/Tao.OpenGl.DLL
----------------------------------------
Tao.Platform.Windows
    Assembly Version: 1.0.0.5
    Win32 Version: 1.0.0.5
    CodeBase: file:///C:/Program%20Files%20(x86)/Coffee_/Tank%20Exporter/Tao.Platform.Windows.DLL
----------------------------------------
Tao.FreeGlut
    Assembly Version: 2.4.0.2
    Win32 Version: 2.4.0.2
    CodeBase: file:///C:/Program%20Files%20(x86)/Coffee_/Tank%20Exporter/Tao.FreeGlut.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.



```

After clicking Continue on the rror dialog boc, it doesn't show the tanks:
![image](https://github.com/user-attachments/assets/3cea53d5-3b68-4a32-8c28-2fea0bc22fd1)

The DLL seems to be missing 32bit dependencies:
[TextureLoader.txt](https://github.com/user-attachments/files/17963322/TextureLoader.txt)

It is a VM, because I do not trust a random exe, but it is just a clean Win11 Installation using 3CPU cores. WoT and a bunch of other stuff runs on it fine.

**Comment by mikeoverbay** [comment]
[TextureLoader.zip](https://github.com/user-attachments/files/18032187/TextureLoader.zip)
Unzip and drop this in the root in the tank exporter app.
Its odd no one else has reported this at the forums.
tnmshouse.com

**Comment by mikeoverbay** [comment]
My app is safe. It does phone home to check for an update and access the API to get tank info.
It should run fine in a VM.
