### ISSUE TITLE
Doesn't want me to make a cool skin :(

### ISSUE THREAD

**Issue by Sparton385** [mikeoverbay/TankExporter#91]
So i was just making a custom skin for the is-6, and i wanted to test to see if it still worked, I changed the gun and the tracks entirely, but everything else was just added/edited.

![Screenshot 2023-08-18 193401](https://github.com/mikeoverbay/TankExporter/assets/124919964/dedd47f7-6d95-4bb7-b609-ef0376255f36)

and when i changed the file type from 2013 to 2009, it was good, then when i tried to import it i got this error

![error screenshot](https://github.com/mikeoverbay/TankExporter/assets/124919964/5ac1ddf4-3f72-41e1-b07d-bb5ed00d304c)

I dont really know what I did that messed it up, but i imagine i did something i wasnt supposed to.

**Comment by Sparton385** [comment]
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Tank_Exporter.modFBX.get_component_index()
   at Tank_Exporter.modFBX.process_fbx_data()
   at Tank_Exporter.modFBX.import_FBX()
   at Tank_Exporter.frmMain.m_Import_FBX_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Saw someone else post something similar, so i dont know if will help but here

**Comment by Sparton385** [comment]
![image](https://github.com/mikeoverbay/TankExporter/assets/124919964/e4e3b5c5-4c61-47fb-9fdd-57b696df67db)

alright i got it to work sort of, by literally removing the muzzle from the 705a i had, it works, no matter what i do, as long as i dont slide the hull over or anything it works, but the one part i want the muzzle, doesnt want to

**Comment by Sparton385** [comment]
The above picture is after removing the actual muzzle from blender, and having a blank, sorry this
![image](https://github.com/mikeoverbay/TankExporter/assets/124919964/c6c7fc87-bf91-4ee1-a0e8-7139697e16a2)

**Comment by Sparton385** [comment]
nah i figured it out, im pretty retarded, i had one to many file types, so see the top right with each object, i had to many and had to reduce it to both tracks and road wheels, hull, turret, and gun for a total of 7 objects.

**Comment by Sparton385** [comment]
close to final, currently need to mess with textures/texture paths.
![image](https://github.com/mikeoverbay/TankExporter/assets/124919964/6cc4491b-6175-4559-b00c-fdcd1256b40f)

Thanks for the easy to use app, really makes the work 1000 times easier!

**Comment by Sparton385** [comment]
Alright so as i was messing around the the textures, i found this out
![image](https://github.com/mikeoverbay/TankExporter/assets/124919964/47bd49d6-ca6f-4e1f-bef4-99acfd71aa95)
![image](https://github.com/mikeoverbay/TankExporter/assets/124919964/210e6ada-563a-4d25-8adc-14e42980e6b0)
So when i have the textures on it is happy, when i dont, well it aparently isnt happy.
the regular is6 tho is good
![image](https://github.com/mikeoverbay/TankExporter/assets/124919964/9ad3ed8b-4642-4874-937a-a1d96327e159)
![image](https://github.com/mikeoverbay/TankExporter/assets/124919964/b7b327d8-9139-4b53-a1e5-7c54a72e4ad6)

**Comment by Sparton385** [comment]
if this helps, when i mirror the parts on blender, it flips them when i change between the textures
![image](https://github.com/mikeoverbay/TankExporter/assets/124919964/e14584b0-28ff-411c-ad6e-7fa616a26418)
![image](https://github.com/mikeoverbay/TankExporter/assets/124919964/9d895153-eb2a-42a9-824d-84b2a4f087d5)

**Comment by mikeoverbay** [comment]
The gun is backwards in the game. In fact all skinned models are backwards as far as the actual geo is concerned.
I flip the model by inverting some of the matrix values to fix this for the FBX export.
This can make them render inside out in other apps so its important that the tool you use is set to render both sides of the model and never change the models matrix.
I hope this helps.
